name = "PowerModelsExtensions"
uuid = "fcef9a4a-e17c-49fa-9a63-772f304ba614"
authors = ["Skyler Reid <skyler.reid2235@gmail.com>"]
version = "0.1.0"

[deps]
HSL_jll = "017b0a0e-03f4-516a-9b91-836bbd1904dd"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"

[compat]
Ipopt = "1"
JSON = "0.21.4"
JuMP = "1"
MathOptInterface = "1"
PowerModels = "0"
